services:
  api:
    container_name: api
    build:
      context: ./src/main/docker/Dockerfile.jvm
    depends_on:
      - db
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_URL=postgresql://db:5432/message-resume
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=message-resume