quarkus:
  datasource:
    db-kind: postgresql 
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    jdbc:
      url: ${DATABASE_URL}
  hibernate-orm:
    database:
      generation: update
  http:
    port: 8080
    cors:
      ~: true
      methods: GET, POST, PUT, DELETE, PATCH, OPTION
      headers: Access-Control-Allow-Headers, Accept, Content-Type, Authorization, X-Skip-Interceptor,  X-Requested-With

"%dev":
  quarkus:
    datasource:
      db-kind: h2 
      username: sa
      jdbc:
        url: jdbc:h2:mem:default
    hibernate-orm:
      database:
        generation: drop-and-create
    http:
      port: 8080
      cors:
        ~: true
        methods: GET, POST, PUT, DELETE, PATCH, OPTION
        headers: Access-Control-Allow-Headers, Accept, Content-Type, Authorization, X-Skip-Interceptor,  X-Requested-With